### PR TITLE
Add unit tests for TLSSocket and TLSSocketWrapper

### PR DESCRIPTION
**Pull request by michalpasztamobica**
This also includes their Datagram counterparts: DTLSSocket and DTLSSocketWrapper.
Coverage missing for timer-related functionality, but this would require more advanced stub development.
The extra (d)tls_test_config.h is necessary for successful compilation without HW support for the mbedtls features in unittests.
I reused the mbedtls stub found in features/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.c and amended it slightly with a few missing functions.

### Description

Introduced unit tests for the newly added classes, depends on https://github.com/ARMmbed/mbed-os/pull/8659

### Pull request type

    [x] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### CODE REVIEW

**Comment by michalpasztamobica** [comment]
@SeppoTakalo , please review and merge if everything is ok.

**Comment by SeppoTakalo** [comment]
For me, this stops in:
```
29: [ RUN      ] TestDTLSSocketWrapper.connect_handshake_fail_ssl_handshake
```

**Comment by michalpasztamobica** [comment]
I could not reproduce the issue on Linux, but I can see it on Windows machine. I will try to find the cause and fix it. Thank you for pointing this out!

**Comment by SeppoTakalo** [comment]
If there is difference between host OS when running unittests, then it usually means that the behaviour relies on zero-initialised variables, which other compiler versions don't do.

So maybe some return codes, event lists, etc are not initialised.

**Comment by michalpasztamobica** [comment]
There was an actual bug in the way I was testing, but Linux was indeed hiding it by how it initializes the memory.
This line in UDPSocket.cpp was causing an issue:
`if (recv >= 0 && _remote_peer && _remote_peer != *address) {`
In Linux _remote_peer had zeroes in the first four bytes and the bool operator returned false and did not check further.
However in Windows the _remote_peer::bool() returned true and the checked that addresses don't match, so it kept waiting for a recv from a correct address. 
I improved the NetworkStack_stub to handle this.
Tests are now passing both on Linux and Windows.
@SeppoTakalo , please check again on your end.

**Comment by SeppoTakalo** [comment]
Hmm.. Are you saying that `SocketAddress` does not zero initialise itself?

I think we rely on quite many operations on that.

**Review by SeppoTakalo — APPROVED** [review]

**Pull request merged**
